### ISSUE TITLE
Update list command for concert and person

### ISSUE THREAD

**Issue by wes-w-z-h** [AY2425S1-CS2103T-F11-1/tp#102]
Right now list command lists all persons only should include concerts as well

**Comment by bbbbcccd** [comment]
Maybe we can create 3 separate commands:
list - lists all persons + concerts
listp - lists all persons
listc - lists all concerts 

Alternatively, we can add optional parameters in the current list command.
E.g. 
list - lists all persons + concerts 
list p/* - lists all persons
list c/* - lists all concerts
