### ISSUE TITLE
[PE-D][Tester B] Incorrect plurality of "Roles" in the displayed message after performing add person command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F11-1/tp#172]
![image.png](https://raw.githubusercontent.com/IzN432/ped/main/files/1e1244fb-58cc-4391-98a9-6e019294e11f.png)

Steps to reproduce:

Perform an addp command. e.g `addp n/Person B p/2345 e/person@email.com a/address r/media`

Issue:

Since only one role is allowed per person, this should be "Role:" instead of "Roles:"

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: IzN432/ped#1

**Comment by hj235** [comment]
Allowed to fix this in v1.6.

![image](https://github.com/user-attachments/assets/4c9c9847-d601-470c-a3da-85d6eea89384)
