### ISSUE TITLE
[PE-D][Tester D] Unable to view full information of concerts

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F11-1/tp#176]
![image.png](https://raw.githubusercontent.com/JovenSoh/ped/main/files/f4434e90-64d6-4828-b35d-21f5ca94ccfd.png)

On smaller screens, there is not a way to view the full information of a concert as the address gets truncated.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: JovenSoh/ped#2

**Comment by hj235** [comment]
Invalid? Can use findc command to stop the truncation

**Comment by wes-w-z-h** [comment]
maybe just dont truncate for all?

**Comment by hj235** [comment]
is that allowed tho
