### ISSUE TITLE
[PE-D][Tester B] Fail to add a concert with name of length 1

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F11-1/tp#183]
![image.png](https://raw.githubusercontent.com/IzN432/ped/main/files/680dcb8d-3c9f-490f-9dc0-cc2464d30486.png)

Steps to reproduce:

Input this command: `addc n/I a/Home d/2024-01-01 1000`

Issue:

Single letter concerts are not too far-fetched. There is nothing in the documentation or error message that suggests a single letter should not be allowed

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: IzN432/ped#3

**Comment by bbbbcccd** [comment]
Similar issue to #227, the regex for name has to be fixed.
