### ISSUE TITLE
Tutorial: tracing code

### ISSUE THREAD

**Issue by karthickkc** [AY2425S1-CS2103T-F11-1/tp#3]
<img width="1470" alt="Screenshot 2024-09-21 at 2 26 05 PM" src="https://github.com/user-attachments/assets/6a194ed9-1e4e-4db6-b1f2-82a365724f24">
<img width="1470" alt="Screenshot 2024-09-21 at 2 27 17 PM" src="https://github.com/user-attachments/assets/e34ef2ef-74a3-45d9-87e0-b95c662c601c">
<img width="1470" alt="Screenshot 2024-09-21 at 2 35 36 PM" src="https://github.com/user-attachments/assets/095d5886-2d10-48f3-8193-94d817da64b4">

**Comment by wes-w-z-h** [comment]
what's this issue for?
