### ISSUE TITLE
Add storage for concerts

### ISSUE THREAD

**Issue by bbbbcccd** [AY2425S1-CS2103T-F11-1/tp#63]
Add storage for concerts, minimally should be an array of JSON objects in the following form: 

  "concerts" :  [
    {
      "name" : String,
      "address" : String,
      "date" : String,
    }, ...
]

At this point, still undecided on how contacts <-> concerts should be stored. Might have to update the storage once decided.

**Comment by wes-w-z-h** [comment]
will be added in #58
